services:
  postgres:
    image: postgres:16-alpine
    container_name: kps_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketplatform
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_pass
    ports:
      - "5432:5432"
    volumes:
      - kps_pgdata:/var/lib/postgresql/data

volumes:
  kps_pgdata:
